INSERT INTO GENRES (NAME) VALUES('Комедия');
INSERT INTO GENRES (NAME) VALUES('Драма');
INSERT INTO GENRES (NAME) VALUES('Мультфильм');
INSERT INTO GENRES (NAME) VALUES('Триллер');
INSERT INTO GENRES (NAME) VALUES('Документальный');
INSERT INTO GENRES (NAME) VALUES('Боевик');

INSERT INTO RATINGS (RATING_NAME) VALUES('G');
INSERT INTO RATINGS (RATING_NAME) VALUES('PG');
INSERT INTO RATINGS (RATING_NAME) VALUES('PG-13');
INSERT INTO RATINGS (RATING_NAME) VALUES('R');
INSERT INTO RATINGS (RATING_NAME) VALUES('NC-17');
