MERGE INTO MPA(MPA_ID, MPA_NAME)
VALUES (1,'18+');

MERGE INTO MPA(MPA_ID, MPA_NAME)
    VALUES (1,'0+');

MERGE INTO MPA(MPA_ID, MPA_NAME)
    VALUES (1,'6+');

MERGE INTO MPA(MPA_ID, MPA_NAME)
    VALUES (1,'12+');

MERGE INTO MPA(MPA_ID, MPA_NAME)
    VALUES (1,'16+');